title: My GitHub Blog
description: Welcome to my personal blog where I share my thoughts and experiences
theme: minima
author: Mahmudul Hossen

url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
github_username: mhossen

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/